USE Projecto_Nicolas;

SET GLOBAL local_infile = true;

-- Cargar datos desde archivos CSV

LOAD DATA INFILE '/structure/data_csv/paises.csv' INTO TABLE Paises
FIELDS TERMINATED BY '%' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/structure/data_csv/paises.csv' INTO TABLE Clientes
FIELDS TERMINATED BY '%'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/structure/data_csv/paises.csv' INTO TABLE Productos
FIELDS TERMINATED BY '%' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/structure/data_csv/paises.csv' INTO TABLE Canales
FIELDS TERMINATED BY '%' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/structure/data_csv/paises.csv' INTO TABLE Departamentos
FIELDS TERMINATED BY '%' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/structure/data_csv/paises.csv' INTO TABLE Empleados
FIELDS TERMINATED BY '%' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/structure/data_csv/paises.csv' INTO TABLE Ventas
FIELDS TERMINATED BY '%' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/structure/data_csv/paises.csv' INTO TABLE Pedidos
FIELDS TERMINATED BY '%' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/structure/data_csv/paises.csv' INTO TABLE Proveedores
FIELDS TERMINATED BY '%' ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
